### ISSUE TITLE
ReConsider the APIs

### ISSUE THREAD

**Issue by niku** [otoyo/pixela_ex#3]
First of all, thank you for creating such a nice library.

I reconsider the pixela_ex apis and found some changes make it better.
However it includes breaking changes, so I propose you changes before implement.

If you feel OK, I will implement this.
Any thoughts?

To make api convenient, the changes follows following principles:
- When it was finished without errors, it returns `{:ok, ____}`. Otherwise it returns `{:error, ___}`
- required parameters bring as arguments
- optional parameters bring as an argument of [Keyword](https://hexdocs.pm/elixir/Keyword.html)

| propose to change | current | new | note |
| - | - | - | - |
| o | `create_user(%{username: username, token: token, agree_terms_of_service: agree_terms_of_service, not_minor: not_minor})` | `create_user(username, token_will_be_used, agree_terms_of_service, not_minor)` | https://pixe.la/#api-detail-post-users |
| o | `update_user(username, token, %{new_token: new_token})` | `update_user(username, token, new_token)` | https://pixe.la/#api-detail-put-user |
| | `delete_user(username, token)` | `delete_user(username, token)` | https://pixe.la/#api-detail-delete-user |
| o | `create_graph(username, token, %{graph_id: graph_id, name: name, unit: unit, type: quantity_type, color: color})` | `create_graph(username, token, id, name, unit, type, color)` | https://pixe.la/#api-detail-post-graphs |
| | `get_graphs(username, token)` | `get_graphs(username, token)` | https://pixe.la/#api-detail-get-graphs |
| o | `graph_url(username, graph_id, %{date: date, mode: mode})` | `get_graph(username, graph_id, date: date, mode: mode)` | https://pixe.la/#api-detail-get-graph |
| o | `update_graph(username, token, graph_id, %{name: name, unit: unit, color: color})` | `update_graph(username, token, graph_id, name: name, unit: unit, color: color, purge_cache_urls: purge_cache_urls)` | https://pixe.la/#api-detail-put-graph |
| | `delete_graph(username, token, graph_id)` | `delete_graph(username, token, graph_id)` | https://pixe.la/#api-detail-delete-graph |
| o | `create_pixel(username, token, graph_id, %{date: date, quantity: quantity})` | `create_pixel(username, token, graph_id, date, quantity)` | https://pixe.la/#api-detail-post-pixels |
| | `get_pixel(username, token, graph_id, date)` | `get_pixel(username, token, graph_id, date)` | https://pixe.la/#api-detail-get-pixel |
| o | `update_pixel(username, token, graph_id, date, %{quantity: quantity})` | `update_pixel(username, token, graph_id, date, quantity)` | https://pixe.la/#api-detail-put-pixel |
| | `increment_pixel(username, token, graph_id)` | `increment_pixel(username, token, graph_id)` | https://pixe.la/#api-detail-pixel-increment |
| | `decrement_pixel(username, token, graph_id)` | `decrement_pixel(username, token, graph_id)` | https://pixe.la/#api-detail-pixel-decrement |
| | `delete_pixel(username, token, graph_id, date)` | `delete_pixel(username, token, graph_id, date)` | https://pixe.la/#api-detail-delete-pixel | 
| o | `create_webhook(username, token, %{graph_id: graph_id, type: countup_type})` | `create_webhook(username, token, graph_id, type)` | https://pixe.la/#api-detail-post-webhooks |
| | `get_webhooks(username, token)` | `get_webhooks(username, token)` | https://pixe.la/#api-detail-get-webhooks |
| | `invoke_webhook(username, webhook_hash)` | `invoke_webhook(username, webhook_hash)` | https://pixe.la/#api-detail-post-webhook |
| | `delete_webhook(username, token, webhook_hash)` | `delete_webhook(username, token, webhook_hash)` | https://pixe.la/#api-detail-delete-webhook |

**Comment by otoyo** [comment]
Sounds good!
After changes, I will publish as major version.
